-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2019-03-14 15:29:21 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE categorie (
    codecategorie   CHAR(1) NOT NULL,
    nomcategorie    VARCHAR2(30),
    couleur         VARCHAR2(20)
);

ALTER TABLE categorie ADD CONSTRAINT categorie_pk PRIMARY KEY ( codecategorie );
ALTER TABLE categorie ADD CONSTRAINT couleur_ck CHECK (couleur in ('blanc', 'rouge', 'bleu', 'vert', 'jaune'));
ALTER TABLE categorie ADD CONSTRAINT couleur_uk UNIQUE(couleur);

CREATE TABLE joueurs2 (
    alias    VARCHAR2(20) NOT NULL,
    nom      VARCHAR2(40),
    prenom   VARCHAR2(40)
);

ALTER TABLE joueurs2 ADD CONSTRAINT joueurs2_pk PRIMARY KEY ( alias );

CREATE TABLE questions (
    numquestion      CHAR(6) NOT NULL,
    enoncequestion   VARCHAR2(60),
    posee            CHAR(1) NOT NULL,
    codecategorie    CHAR(1),
    numreponse       CHAR(8) NOT NULL
);

ALTER TABLE questions ADD CONSTRAINT questions_pk PRIMARY KEY ( numquestion );
ALTER TABLE questions ADD CONSTRAINT posee_ck CHECK (posee in('o', 'n'));

CREATE TABLE reponses (
    numreponse      CHAR(8) NOT NULL,
    description     VARCHAR2(60),
    estbonne        CHAR(1) NOT NULL,
    numquestion     CHAR(6),
    codecategorie   CHAR(1) NOT NULL
);

ALTER TABLE reponses ADD CONSTRAINT reponses_pk PRIMARY KEY ( numreponse );
ALTER TABLE reponses ADD CONSTRAINT estbonne_ck CHECK (estbonne in ('o', 'n'));

CREATE TABLE scores (
    codecategorie   CHAR(1) NOT NULL,
    alias           VARCHAR2(20) NOT NULL,
    score           NUMBER(4) NOT NULL
);

ALTER TABLE scores ADD CONSTRAINT scores_pk PRIMARY KEY ( codecategorie,
                                                          alias );

ALTER TABLE questions
    ADD CONSTRAINT questions_reponses_fk FOREIGN KEY ( numreponse )
        REFERENCES reponses ( numreponse );

ALTER TABLE reponses
    ADD CONSTRAINT reponses_categorie_fk FOREIGN KEY ( codecategorie )
        REFERENCES categorie ( codecategorie );

ALTER TABLE scores
    ADD CONSTRAINT scores_categorie_fk FOREIGN KEY ( codecategorie )
        REFERENCES categorie ( codecategorie );

ALTER TABLE scores
    ADD CONSTRAINT scores_joueurs_fk FOREIGN KEY ( alias )
        REFERENCES joueurs ( alias );

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
