create or replace TRIGGER INSERTION_QUESTION 
BEFORE INSERT ON QUESTIONS 
FOR EACH ROW
BEGIN
  IF :NEW.CODECATEGORIE = '5' THEN
    RAISE_APPLICATION_ERROR(-20000, 'lA CATEGORIE UNIVERSELLE NE PEUT PAS AVOIR DE QUESTIONS');
  END IF;
END;